PRIVATE_KEY: "${ssm:private-key}"
PUBLIC_KEY: "${ssm:public-key}"
TOKEN_EXPIRATION_TIME: "${ssm:token-expiration-time}"
DATABASE_USERNAME: "${ssm:database-username-hackathon}"
DATABASE_PASSWORD: "${ssm:database-password-hackathon}"
DATABASE_HOST: "${ssm:database-host-hackathon}"
DATABASE_PORT: "${ssm:database-port-hackathon}"
DATABASE_NAME: "${ssm:database-name-hackathon}"

PASSWORD_SALT: "${ssm:password-salt}"
